name: Build and test

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'master' }}

jobs:

  build-mac:
    strategy:
      matrix:
        include:
          - { os: macos-13, arch: x86_64 }
    name: Mac OS (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Fix Python symlinks
        run: |
          find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -delete -print
          brew unlink python && brew link --overwrite python
      - name: Work around pkg-config issue
        run: brew uninstall --ignore-dependencies --force pkg-config@0.29.2
      - name: Install dependencies
        run: brew install llvm check automake libffi pkg-config zstd
      - name: Generate configure script
        run: ./autogen.sh
      - name: Configure
        run: |
          mkdir build && cd build
          ../configure --with-llvm=$(brew --prefix llvm)/bin/llvm-config \
               --enable-debug --disable-lto
      - name: Build
        run: make -C build -j $(sysctl -n hw.logicalcpu)
      - name: Test
        run: make -C build check
      - name: Dist clean
        run: make -C build distclean
      - name: Configure for release
        run: |
          cd build
          ../configure --with-llvm=$(brew --prefix llvm)/bin/llvm-config \
               --disable-debug
      - name: Build release
        run: make -C build -j $(sysctl -n hw.logicalcpu)